name: Deploy Dev Infraestructure
on:
    push:
      branches:
        -main
      paths:
        - 'env/dev/**'
        - 'modules/**'

env:
  ARM_CLIENT_ID: "${{secrets.ARM_CLIENT_ID}}"
  ARM_CLIENT_SECRET: "${{secrets.ARM_CLIENT_SECRET}}"
  ARM_SUBSCRIPTION_ID: "${{secrets.ARM_SUBSCRIPTION_ID}}"
  ARM_TENANT_ID: "${{secrets.ARM_TENANT_ID}}"
  TF_VAR_mongo_url: "${{secrets.TF_VAR_mongo_url}}"
  TF_VAR_port: "${{secrets.TF_VAR_port}}"
  TF_VAR_mongo_db: "${{secrets.TF_VAR_mongo_db}}"
  TF_VAR_mail_secret_key: "${{secrets.TF_VAR_mail_secret_key}}"
  TF_VAR_mapbox_access_token: "${{secrets.TF_VAR_mapbox_access_token}}"
  TF_VAR_mail_service: "${{secrets.TF_VAR_mail_service}}"
  TF_VAR_mail_user: "${{secrets.TF_VAR_mail_user}}"
  TF_VAR_init_root_username: "${{secrets.TF_VAR_init_root_username}}"
  TF_VAR_init_root_password: "${{secrets.TF_VAR_init_root_password}}"
  TF_VAR_domain: "${{secrets.TF_VAR_domain}}"

  
  


jobs:
    terraform-plan-apply:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Create SSH Keys from secrets
              run: |
                mkdir -p ./env/dev/keys
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./env/dev/keys/712incident_server
                echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./env/dev/keys/712incident_server.put
                chmod 777 ./env/dev/keys/712incident_server
                chmod 777 ./env/dev/keys/712incident_server.pub

            - name: Terraform setup
              uses: hashicorp/terraform@v2
              with:
                terraformm_version: 1.9.6
                terraform_wrapper: false
            
            - name:  Terraform init
              run: terraform -chdir=env/dev init

            - name: Terraform format
              run: terraform -chdir=env/dev fmt

            - name: Terraform plan
              run:  terraform -chdir=env/dev plan


# Crear los archivios .incident_server.pub y el normalito